---
kind: pipeline
type: docker
name: fmt

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/drone
  settings:
    task: fmt

---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/drone
  settings:
    task: lint

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

- name: gh-pages
  image: letfn/drone-hugo
  settings:
    github_pages: true

depends_on:
- build

...
